### ISSUE TITLE
地图生成失败

### ISSUE THREAD

**Issue by cc2562** [LiteLDev/BDSLM#35]
在使用插件时 无法生成地图

```
17:37:49 ERROR [BDSLM] 地图生成失败：
[17:37:48 INF] (Web) World path: ./worlds/Bedrock level
[17:37:48 INF] (Web) Dimension: minecraft:overworld
Unhandled exception. System.Exception: Cannot load level.dat from "./worlds/Bedrock level\level.dat"
   at Unmined.Level.DataSources.Bedrock.BedrockWorld.InitializeAsync(CancellationToken ctsToken, IProgressHandler progressHandler)
   at Unmined.Level.DataSources.Bedrock.BedrockWorld.Open(String path, CancellationToken ctsToken, IProgressHandler progressHandler)
   at Unmined.Level.DataSources.World.GetWorldAsync(String path, CancellationToken ctsToken, IProgressHandler progressHandler)
   at Unmined.WebExport.WebMapExport.RunAsync(CancellationToken ctsToken, IProgressHandler progressHandler)
   at Unmined.Cmd.Web.WebRenderer.RunAsync()
   at Unmined.Cmd.Web.WebModule.<>c__DisplayClass8_1.<<RunAsync>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at Unmined.Cmd.Web.WebModule.RunAsync(String[] args)
   at Unmined.Cmd.ModuleManager.RunAsync(String[] args)
   at Unmined.Cmd.Program.Main(String[] args)
   at Unmined.Cmd.Program.<Main>(String[] args)

```

服务器信息：
Version 1.19.41.01(ProtocolVersion 557) with LiteLoaderBDS 2.8.1+402b4a5

**Comment by xinchenxpc** [comment]
我也遇到了相同的问题

**Comment by pa733** [comment]
感谢反馈，正在处理

**Comment by pa733** [comment]
已在最新提交中修复，请测试
如仍存在此问题，您可以重新激活此issue

**Comment by OEOTYAN** [comment]
BDS 1.19.61.01 , LL 2.10.0 遇到了同样的问题

**Comment by OEOTYAN** [comment]
已解决，下载最新版unmined替换即可。

**Comment by bao3** [comment]
> 已解决，下载最新版unmined替换即可。

哪里可以下载这个版本。我在 https://jenkins.bllxl.com/job/LiteLDev/job/BDSLM/job/main/ 只看到 2 个月前的版本。

**Comment by OEOTYAN** [comment]
> > 已解决，下载最新版unmined替换即可。
> 
> 哪里可以下载这个版本。我在 https://jenkins.bllxl.com/job/LiteLDev/job/BDSLM/job/main/ 只看到 2 个月前的版本。

unmined官网
